SEED_EQUIPMENT = [
    {
        "equipment_id": "EQ-000001",
        "name": "一号数控机床",
        "equipment_type": "CNC",
        "production_line_id": "LINE-01",
        "location": "一车间 A 区",
        "manufacturer": "示例机床厂",
        "model": "CNC-X1000",
        "responsible_department": "机加车间",
        "current_status": "RUNNING",
        "enabled": True,
    },
    {
        "equipment_id": "EQ-000002",
        "name": "二号加工中心",
        "equipment_type": "MACHINING_CENTER",
        "production_line_id": "LINE-01",
        "location": "一车间 B 区",
        "manufacturer": "示例机床厂",
        "model": "MC-500",
        "responsible_department": "机加车间",
        "current_status": "STOPPED",
        "enabled": True,
    },
    {
        "equipment_id": "EQ-000003",
        "name": "三号冷镦机",
        "equipment_type": "COLD_HEADER",
        "production_line_id": "LINE-02",
        "location": "二车间 C 区",
        "manufacturer": "示例标准件厂",
        "model": "CH-200",
        "responsible_department": "标准件车间",
        "current_status": "TRIAL_RUNNING",
        "enabled": True,
    },
]
