from enum import Enum


class EquipmentStatus(str, Enum):
    RUNNING = "RUNNING"
    WARNING = "WARNING"
    STOPPED = "STOPPED"
    MAINTAINING = "MAINTAINING"
    TRIAL_RUNNING = "TRIAL_RUNNING"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WarningStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    LINKED_TO_ORDER = "LINKED_TO_ORDER"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


class WorkOrderStatus(str, Enum):
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    PENDING_ASSIGNMENT = "PENDING_ASSIGNMENT"
    PENDING_ACCEPTANCE = "PENDING_ACCEPTANCE"
    PENDING_MAINTENANCE = "PENDING_MAINTENANCE"
    MAINTAINING = "MAINTAINING"
    WAITING_PARTS = "WAITING_PARTS"
    PENDING_INSPECTION = "PENDING_INSPECTION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class WorkOrderAction(str, Enum):
    CONFIRM = "CONFIRM"
    ASSIGN = "ASSIGN"
    ACCEPT = "ACCEPT"
    START = "START"
    WAIT_FOR_PARTS = "WAIT_FOR_PARTS"
    RESUME = "RESUME"
    SUBMIT_FOR_INSPECTION = "SUBMIT_FOR_INSPECTION"
    PASS_INSPECTION = "PASS_INSPECTION"
    REJECT_INSPECTION = "REJECT_INSPECTION"
    CANCEL = "CANCEL"


class WorkOrderPriority(str, Enum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"


class WorkOrderSource(str, Enum):
    WARNING = "WARNING"
    MANUAL = "MANUAL"
    INSPECTION = "INSPECTION"


class SpareRequestStatus(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    RESERVED = "RESERVED"
    ISSUED = "ISSUED"
    PARTIALLY_RETURNED = "PARTIALLY_RETURNED"
    CLOSED = "CLOSED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class SpareRequestAction(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    RESERVE = "RESERVE"
    ISSUE = "ISSUE"
    RETURN = "RETURN"
    CLOSE = "CLOSE"
    CANCEL = "CANCEL"


class MaintenanceResult(str, Enum):
    RECOVERED = "RECOVERED"
    PARTIALLY_RECOVERED = "PARTIALLY_RECOVERED"
    NOT_RECOVERED = "NOT_RECOVERED"


class RoleCode(str, Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    EQUIPMENT_OPERATOR = "EQUIPMENT_OPERATOR"
    WARNING_ANALYST = "WARNING_ANALYST"
    MAINTENANCE_SUPERVISOR = "MAINTENANCE_SUPERVISOR"
    MAINTENANCE_ENGINEER = "MAINTENANCE_ENGINEER"
    WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER"
    INSPECTOR = "INSPECTOR"


# 风险等级 -> 工单优先级（契约 shared-enums.json 已定义）
RISK_TO_PRIORITY = {
    RiskLevel.LOW: WorkOrderPriority.P4,
    RiskLevel.MEDIUM: WorkOrderPriority.P3,
    RiskLevel.HIGH: WorkOrderPriority.P2,
    RiskLevel.CRITICAL: WorkOrderPriority.P1,
}